package cloud.icode.onlinesubmit.model.dto;

import lombok.Data;

import java.util.Date;

@Data
public class UploadManuscriptRequest {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.title
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.description
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.user_id
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.status
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    private Integer status;

    private Date date;
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.cover_img
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    private String coverImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.manuscript_file
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    private String manuscriptFile;
}