package cloud.icode.onlinesubmit.model.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.constraints.NotNull;
import java.util.Date;

@Data
@ApiModel(description = "用户上传文稿请求体")
public class UploadManuscriptRequest {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.title
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    @ApiModelProperty(name = "标题",required = true)
    @NotNull(message = "标题不能为空")
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.description
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    @ApiModelProperty(name = "描述",required = true)
    @NotNull(message = "描述不能为空")
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.user_id
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.status
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    private Integer status;

    @ApiModelProperty(name = "日期",required = true)
    @NotNull(message = "日期不能为空")
    private Date date;
    @ApiModelProperty(name = "时间",required = true)
    @NotNull(message = "时间不能为空")
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.cover_img
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    @ApiModelProperty(name = "稿件封面",required = true)
    private String coverImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.manuscript_file
     *
     * @mbg.generated Fri Jan 17 12:27:05 CST 2025
     */
    @ApiModelProperty(name = "稿件文件",required = true)
    private String manuscriptFile;
}