package cloud.icode.onlinesubmit.model.dto;

import lombok.Data;

import javax.validation.constraints.*;

/**
 * 作者: 杨振坤
 * 创建日期: 2025/1/5
 * 文件描述: UserLoginRequest
 */
@Data
public class UserRegisterRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated Sun Jan 05 14:43:58 CST 2025
     */
    @NotNull(message = "昵称不能为空")
    //@Pattern(regexp = UserConstant.ILLEGAL_CHARACTER)
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Sun Jan 05 14:43:58 CST 2025
     */
    @NotNull(message = "用户名不能为空")
    //@Pattern(regexp = UserConstant.ILLEGAL_CHARACTER)
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sun Jan 05 14:43:58 CST 2025
     */
    @NotNull(message = "密码不能为空")
    @Size(min = 6,max = 16,message = "长度不符合规范")
    private String password;

    @NotNull(message = "密码不能为空")
    @Size(min = 6,max = 16,message = "长度不符合规范")
    private String requirePassword;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Sun Jan 05 14:43:58 CST 2025
     */
    @Email(message = "不符合邮箱格式")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbg.generated Sun Jan 05 14:43:58 CST 2025
     */
    @NotNull(message = "手机号不能为空")
    @Size(min = 11,max = 11)
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated Sun Jan 05 14:43:58 CST 2025
     */
    @NotNull(message = "地址不能为空")
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Sun Jan 05 14:43:58 CST 2025
     */
    @NotNull(message = "角色信息不能为空")
    @Min(value = 0,message = "角色信息不对")
    @Max(value = 3,message = "角色信息不对")
    private Integer role;

}
