# 应用服务 WEB 访问端口
server:
  port: 8081
  servlet:
    context-path: '/api'

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_boot_manuscript
    username: root
    password: yzk

# 配置mybatis
mybatis:
  mapper-locations: /mybatis/*.xml

# 稿件属性配置
file:
  upload:
    max: 2097152
    min: 1
  manuscript:
    suffix: pdf,doc,docx
  img:
    suffix: png,jpg,pdf,jpeg

