# 应用服务 WEB 访问端口
server:
  port: 8082
  servlet:
    context-path: '/api'

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_boot_manuscript
    username: root
    password: yzk

# 配置mybatis
mybatis:
  mapper-locations: /mybatis/*.xml



