package cloud.icode.onlinesubmit.model.vo;

import lombok.Data;

import java.util.List;

/**
 * 作者: 杨振坤
 * 创建日期: 2025/1/12 上午11:43
 * 文件描述: MenuVo
 */
@Data
public class MenuVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Sun Jan 12 10:53:56 CST 2025
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbg.generated Sun Jan 12 10:53:56 CST 2025
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbg.generated Sun Jan 12 10:53:56 CST 2025
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.path
     *
     * @mbg.generated Sun Jan 12 10:53:56 CST 2025
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbg.generated Sun Jan 12 10:53:56 CST 2025
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.user_id
     *
     * @mbg.generated Sun Jan 12 10:53:56 CST 2025
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent_id
     *
     * @mbg.generated Sun Jan 12 10:53:56 CST 2025
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.label
     *
     * @mbg.generated Sun Jan 12 10:53:56 CST 2025
     */
    private String label;

    /**
     * 子菜单
     */
    private List<MenuVo> children;
}
