package cloud.icode.onlinesubmit.model.vo;

import lombok.Data;

import java.util.Date;

/**
 * 作者: 杨振坤
 * 创建日期: 2025/1/13 上午11:48
 * 文件描述: OperateLogVo
 */
@Data
public class OperateLogVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.id
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.name
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.method_name
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.url
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.request_method
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String requestMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.ip_addr
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String ipAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.request_time
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private Date requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.operator
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String operator;
}
