package cloud.icode.onlinesubmit.dao;

import cloud.icode.onlinesubmit.model.Manuscript;
import cloud.icode.onlinesubmit.model.ManuscriptExample;
import cloud.icode.onlinesubmit.model.ManuscriptWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManuscriptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    long countByExample(ManuscriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    int deleteByExample(ManuscriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    int insert(ManuscriptWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    int insertSelective(ManuscriptWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    List<ManuscriptWithBLOBs> selectByExampleWithBLOBs(ManuscriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    List<Manuscript> selectByExample(ManuscriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    ManuscriptWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    int updateByExampleSelective(@Param("row") ManuscriptWithBLOBs row, @Param("example") ManuscriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") ManuscriptWithBLOBs row, @Param("example") ManuscriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    int updateByExample(@Param("row") Manuscript row, @Param("example") ManuscriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    int updateByPrimaryKeySelective(ManuscriptWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(ManuscriptWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manuscript
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    int updateByPrimaryKey(Manuscript row);
}