package cloud.icode.onlinesubmit.dao;

import cloud.icode.onlinesubmit.model.OperateLog;
import cloud.icode.onlinesubmit.model.OperateLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    long countByExample(OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    int deleteByExample(OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    int insert(OperateLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    int insertSelective(OperateLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    List<OperateLog> selectByExample(OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    OperateLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    int updateByExampleSelective(@Param("row") OperateLog row, @Param("example") OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    int updateByExample(@Param("row") OperateLog row, @Param("example") OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    int updateByPrimaryKeySelective(OperateLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    int updateByPrimaryKey(OperateLog row);
}