package cloud.icode.onlinesubmit.model;

public class ManuscriptWithBLOBs extends Manuscript {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.cover_img
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    private String coverImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.manuscript_file
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    private String manuscriptFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manuscript.cover_img
     *
     * @return the value of manuscript.cover_img
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public String getCoverImg() {
        return coverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manuscript.cover_img
     *
     * @param coverImg the value for manuscript.cover_img
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public void setCoverImg(String coverImg) {
        this.coverImg = coverImg == null ? null : coverImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manuscript.manuscript_file
     *
     * @return the value of manuscript.manuscript_file
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public String getManuscriptFile() {
        return manuscriptFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manuscript.manuscript_file
     *
     * @param manuscriptFile the value for manuscript.manuscript_file
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public void setManuscriptFile(String manuscriptFile) {
        this.manuscriptFile = manuscriptFile == null ? null : manuscriptFile.trim();
    }
}