package cloud.icode.onlinesubmit.model;

import java.util.Date;

public class Manuscript {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.id
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.title
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.description
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.user_id
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.status
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.submit_time
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    private Date submitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.create_time
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.update_time
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manuscript.is_delete
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manuscript.id
     *
     * @return the value of manuscript.id
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manuscript.id
     *
     * @param id the value for manuscript.id
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manuscript.title
     *
     * @return the value of manuscript.title
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manuscript.title
     *
     * @param title the value for manuscript.title
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manuscript.description
     *
     * @return the value of manuscript.description
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manuscript.description
     *
     * @param description the value for manuscript.description
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manuscript.user_id
     *
     * @return the value of manuscript.user_id
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manuscript.user_id
     *
     * @param userId the value for manuscript.user_id
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manuscript.status
     *
     * @return the value of manuscript.status
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manuscript.status
     *
     * @param status the value for manuscript.status
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manuscript.submit_time
     *
     * @return the value of manuscript.submit_time
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manuscript.submit_time
     *
     * @param submitTime the value for manuscript.submit_time
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manuscript.create_time
     *
     * @return the value of manuscript.create_time
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manuscript.create_time
     *
     * @param createTime the value for manuscript.create_time
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manuscript.update_time
     *
     * @return the value of manuscript.update_time
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manuscript.update_time
     *
     * @param updateTime the value for manuscript.update_time
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manuscript.is_delete
     *
     * @return the value of manuscript.is_delete
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manuscript.is_delete
     *
     * @param isDelete the value for manuscript.is_delete
     *
     * @mbg.generated Tue Jan 21 19:55:46 CST 2025
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}