package cloud.icode.onlinesubmit.model;

import java.util.Date;

public class OperateLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.id
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.name
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.method_name
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.url
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.request_method
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String requestMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.ip_addr
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String ipAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.request_time
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private Date requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.operator
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.create_time
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.update_time
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.is_delete
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.id
     *
     * @return the value of operate_log.id
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.id
     *
     * @param id the value for operate_log.id
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.name
     *
     * @return the value of operate_log.name
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.name
     *
     * @param name the value for operate_log.name
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.method_name
     *
     * @return the value of operate_log.method_name
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.method_name
     *
     * @param methodName the value for operate_log.method_name
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.url
     *
     * @return the value of operate_log.url
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.url
     *
     * @param url the value for operate_log.url
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.request_method
     *
     * @return the value of operate_log.request_method
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.request_method
     *
     * @param requestMethod the value for operate_log.request_method
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod == null ? null : requestMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.ip_addr
     *
     * @return the value of operate_log.ip_addr
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.ip_addr
     *
     * @param ipAddr the value for operate_log.ip_addr
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.request_time
     *
     * @return the value of operate_log.request_time
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.request_time
     *
     * @param requestTime the value for operate_log.request_time
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.operator
     *
     * @return the value of operate_log.operator
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.operator
     *
     * @param operator the value for operate_log.operator
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.create_time
     *
     * @return the value of operate_log.create_time
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.create_time
     *
     * @param createTime the value for operate_log.create_time
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.update_time
     *
     * @return the value of operate_log.update_time
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.update_time
     *
     * @param updateTime the value for operate_log.update_time
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.is_delete
     *
     * @return the value of operate_log.is_delete
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.is_delete
     *
     * @param isDelete the value for operate_log.is_delete
     *
     * @mbg.generated Fri Jan 10 21:42:33 CST 2025
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}